### Tensors

In [1]:
# A future statement is a directive to the compiler that a particular module should be compiled using syntax or 
# semantics that will be available in a specified future release of Python. The future statement is intended to 
# ease migration to future versions of Python that introduce incompatible changes to the language. It allows use 
# of the new features on a per-module basis before the release in which the feature becomes standard.
from __future__ import print_function
import torch

In [2]:
x = torch.empty(4,5)
x

tensor(1.00000e-33 *
       [[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0001,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  5.8563,  0.0000,  0.0000,  0.0000]])

In [3]:
x = torch.rand(3,3)
x

tensor([[ 0.8836,  0.3876,  0.3025],
        [ 0.7950,  0.4879,  0.0346],
        [ 0.8094,  0.8506,  0.0128]])

In [4]:
x = torch.zeros(2,2,dtype=torch.long)
x

tensor([[ 0,  0],
        [ 0,  0]])

In [5]:
x = torch.tensor([[3,4,5.9],[9.1,2.3,3]])
x

tensor([[ 3.0000,  4.0000,  5.9000],
        [ 9.1000,  2.3000,  3.0000]])

In [6]:
x = x.new_ones(3,2,dtype=torch.double)
x

tensor([[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]], dtype=torch.float64)

In [7]:
# Returns a tensor with the same size as input that is filled with random numbers from a normal distribution 
# with mean 0 and variance 1.
x = torch.randn_like(x,dtype=torch.float)
x

tensor([[-0.9568,  0.0288],
        [ 1.1736,  0.7387],
        [ 2.0611,  0.4307]])

In [8]:
x.size()

torch.Size([3, 2])

### Operations

In [9]:
y = torch.rand(3,2)
y

tensor([[ 0.4073,  0.6181],
        [ 0.5693,  0.1428],
        [ 0.1128,  0.6505]])

In [10]:
x+y

tensor([[-0.5495,  0.6469],
        [ 1.7429,  0.8815],
        [ 2.1739,  1.0812]])

In [11]:
# Other way of performing addition
torch.add(x,y)

tensor([[-0.5495,  0.6469],
        [ 1.7429,  0.8815],
        [ 2.1739,  1.0812]])

In [12]:
# Providing an output tensor as arg
result = torch.empty(3,2)
torch.add(x,y, out = result)
result

tensor([[-0.5495,  0.6469],
        [ 1.7429,  0.8815],
        [ 2.1739,  1.0812]])

In [13]:
# Addition in place
y.add_(x)
y

tensor([[-0.5495,  0.6469],
        [ 1.7429,  0.8815],
        [ 2.1739,  1.0812]])

In [14]:
x[:,1]

tensor([ 0.0288,  0.7387,  0.4307])

In [15]:
# Resizing or Reshaping a tensor
x = torch.randn(3,3)
y = x.view(9)
y.size()

torch.Size([9])

In [16]:
z = x.view(-1,9)
z.size()

torch.Size([1, 9])

In [17]:
# Only for one element tensor
x = torch.randn(1)
x.item()

0.15246231853961945

### Numpying

In [18]:
# Convert torch tensor to numpy array
x = torch.ones(1,4)
x

tensor([[ 1.,  1.,  1.,  1.]])

In [19]:
y = x.numpy()
y

array([[1., 1., 1., 1.]], dtype=float32)

In [20]:
# Changing the value of x will change the value of y as well
x.add_(1)
x

tensor([[ 2.,  2.,  2.,  2.]])

In [21]:
y

array([[2., 2., 2., 2.]], dtype=float32)

In [22]:
# Convert numpy array to torch tensor
import numpy as np
a = np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [23]:
b = torch.from_numpy(a)
b

tensor([[ 1.,  1.],
        [ 1.,  1.]], dtype=torch.float64)

In [24]:
np.add(a,1,out=a)

array([[2., 2.],
       [2., 2.]])

In [25]:
b

tensor([[ 2.,  2.],
        [ 2.,  2.]], dtype=torch.float64)