### Tensors

In [1]:
# A future statement is a directive to the compiler that a particular module should be compiled using syntax or 
# semantics that will be available in a specified future release of Python. The future statement is intended to 
# ease migration to future versions of Python that introduce incompatible changes to the language. It allows use 
# of the new features on a per-module basis before the release in which the feature becomes standard.
from __future__ import print_function
import torch

In [2]:
x = torch.empty(4,5)
x

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  1.2612e-44],
        [-0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  1.4013e-45],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  1.1704e-41,  0.0000e+00,  2.2369e+08]])

In [3]:
x = torch.rand(3,3)
x

tensor([[ 0.8024,  0.8698,  0.6660],
        [ 0.9870,  0.9901,  0.5369],
        [ 0.7657,  0.7203,  0.5373]])

In [4]:
x = torch.zeros(2,2,dtype=torch.long)
x

tensor([[ 0,  0],
        [ 0,  0]])

In [6]:
x = torch.tensor([[3,4,5.9],[9.1,2.3,3]])
x

tensor([[ 3.0000,  4.0000,  5.9000],
        [ 9.1000,  2.3000,  3.0000]])

In [8]:
x = x.new_ones(3,2,dtype=torch.double)
x

tensor([[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]], dtype=torch.float64)

In [10]:
# Returns a tensor with the same size as input that is filled with random numbers from a normal distribution 
# with mean 0 and variance 1.
x = torch.randn_like(x,dtype=torch.float)
x

tensor([[-1.3964,  1.4914],
        [ 0.2791,  0.4745],
        [ 1.5803,  0.4713]])

In [11]:
x.size()

torch.Size([3, 2])

### Operations

In [12]:
y = torch.rand(3,2)
y

tensor([[ 0.5183,  0.4276],
        [ 0.6545,  0.5127],
        [ 0.5800,  0.4550]])

In [13]:
x+y

tensor([[-0.8781,  1.9189],
        [ 0.9336,  0.9872],
        [ 2.1603,  0.9263]])

In [14]:
# Other way of performing addition
torch.add(x,y)

tensor([[-0.8781,  1.9189],
        [ 0.9336,  0.9872],
        [ 2.1603,  0.9263]])

In [15]:
# Providing an output tensor as arg
result = torch.empty(3,2)
torch.add(x,y, out = result)
result

tensor([[-0.8781,  1.9189],
        [ 0.9336,  0.9872],
        [ 2.1603,  0.9263]])

In [16]:
# Addition in place
y.add_(x)
y

tensor([[-0.8781,  1.9189],
        [ 0.9336,  0.9872],
        [ 2.1603,  0.9263]])

In [17]:
x[:,1]

tensor([ 1.4914,  0.4745,  0.4713])